### ISSUE TITLE
5-та задача

### ISSUE THREAD

**Issue by vladko194** [theVelislavKolesnichenko/CPlusPlusBasic#2]
по какъв начин трябва да изведем трябва ли да е с цикъл или както решим ние
1  6  11
2  7  12
3  8
4  9
5 10

**Comment by theVelislavKolesnichenko** [comment]
Трябва да се направи за N елемента в масива, което означава че може да е с повече от 12 или по малко от 12 елемента масива. Решението е по ваш избор важно е да се изпълнява условието на задачата. Според мен с цикъл ще ви е най-лесно, но съм отворен за оригинални решения.
