### ISSUE TITLE
Visual Studio дава error

### ISSUE THREAD

**Issue by vladko194** [theVelislavKolesnichenko/CPlusPlusBasic#3]
Error	C4996	'strupr': The POSIX name for this item is deprecated. Instead, use the ISO C and C++ conformant name: _strupr. Дава ми този error като използвам strupr горе съм инклуднал библиотеката

**Comment by theVelislavKolesnichenko** [comment]
Изпробвайте името _strupr ще обновя списъка с функции с имената за последната версия на VS

**Comment by vladko194** [comment]
И с това нестава пробвах и с _strupr_s и ми връща 0

**Comment by vladko194** [comment]
Всъщност с _strupr_s стана

**Comment by vladko194** [comment]
no instance of overloaded function matches the argument list            argument types are: (char) в крайна сметка изписва това

**Comment by theVelislavKolesnichenko** [comment]
Промених условието на задачата. Функциите _strupr_s(str, count) и _strlwr_s(str, count) изпълняват условието на задачата. Те променят самата стойност на масива и функцията за преобразуване ще е от тип void.

**Comment by vladko194** [comment]
А 1ва задача със switch ли трябва да е

**Comment by theVelislavKolesnichenko** [comment]
кода на големите букви -26 дава номера им в азбуката, за малките трябва да е -96

във втора задача символите, който не могат да се изведат ги прескочете

**Comment by vladko194** [comment]
Извинете ще може ли пример за При извеждането подредете стойностите в правилни редове и колони с два знака след десетичнта запетая. защото немога да разбера какво точно се изисква от нас

**Comment by theVelislavKolesnichenko** [comment]
Пример за  не правилни колони и редове:
```
1.45 45.78 0.8 4.1
45.89 4.57 78.78 45.5
45.9 4.5 7.78 5.5
```
Пример за  не правилни колони и редове:
```
 1.45 45.78  0.80  4.10
45.89  4.57 78.78 45.50
45.90  4.50  7.78  5.50
```
