### ISSUE TITLE
Главният и второстепенният диагонал трябва ли да са в диагонал или просто трябва да се изведат числата им в 1 ред

### ISSUE THREAD

**Issue by vladko194** [theVelislavKolesnichenko/CPlusPlusBasic#4]

**Comment by theVelislavKolesnichenko** [comment]
В диагонал ще е по интересно

**Comment by vladko194** [comment]
А може ли елементите да се изкарват един по един със съответния setw или трябва и цикъл

**Comment by theVelislavKolesnichenko** [comment]
Трудно ли ще е с цикъл ?

когато се извежда второстепенния диагонал номера на реда и на колоната съвпадат а стойността на изместване трябва да е номера на колоната + 1 нужен е само един цикъл

когато се извежда главния диагонал ще са ни нужни две променливи но 1 цикъл. едната променлива ще брой редовете от 0 до N другата ще брой колоните от N до 0. а условието трябва да е row < N && col > 0

пробвайте с цикъл

**Comment by vladko194** [comment]
Изтрих коментара направих го по друг начин от това както сте го написали но е с цикъл да попитам Намиране сумата от елементите по колони от 3та задача трябва да се намери на всяка колона по отделно и после да се намери общият им или трябва да се намери и на 2те наведнъж

**Comment by vladko194** [comment]
като цяло за 4тата функция може ли някакъв пример какво трябва да се изведе

**Comment by theVelislavKolesnichenko** [comment]
Погледнете условието сега

за всяка колона трябва да се намери сумата от елементите и.
в масив се записват сумите който са намерени за всяка колона
за да може да се изведат стойностите на този масив трябва да се направи функция

**Comment by vladko194** [comment]
двете колони после събират ли се или трябва по отделно да се изведат

**Comment by theVelislavKolesnichenko** [comment]
по отделно

**Comment by SimeonStoinev** [comment]
Мисля, че главния диагонал би следвало да е, както сте дали примера на втора задача:
5
 5
  5
   5

А второстепенния диагонал обратно:
   5
  5
 5
5

Или аз греша?

**Comment by theVelislavKolesnichenko** [comment]
Да прав сте, ще го коригирам, но тези които са пратили вече домашното ще го смятам за вярно без значение кой от двата са използвали
