### ISSUE TITLE
Осмо домашно

### ISSUE THREAD

**Issue by mish0501** [theVelislavKolesnichenko/CPlusPlusBasic#5]
От 7 задача надолу масивите матрици ли са и с каква големина на редовете и колоните?

**Comment by theVelislavKolesnichenko** [comment]
От седма задача до десета са едномерни масиви
вие изберете размера им

**Comment by mish0501** [comment]
За 10 задача ще може ли малко разяснения или някакъв пример?

**Comment by theVelislavKolesnichenko** [comment]
Извинете заблудих ви в предходния си отговор 10 задача е с матрица

Имаме матрица от вида:

1 2 3
4 5 6

средната стойност от елементите на първи ред е 2
средната стойност от елементите на втория ред е 5

за да са подредени редовете на матрицата в низходяш ред по средната стойност, означава че матрицата трябва да евъв вида

4 5 6
1 2 3

следователно след като знаем че ред 1 - средната стойност е 2 а на ред 2 средната стойност е 5

елемента с индекси mat[0][0] трябва да се размени с елемента с индекси mat[1][0]
елемента с индекси mat[0][1] трябва да се размени с елемента с индекси mat[1][1]
елемента с индекси mat[0][2] трябва да се размени с елемента с индекси mat[1][2]


Предлагам ви да подходите по следния начин
- направете си функция която да намира средната стойност от елементите в масив
- след товва във функцията за подреждането
        направете цикъл който да обхожда редовете на матрицата 
                            for(int row=0; row < rows - 1; row++)
                                    в този цикъл намирате средната стойност на ред 0
                                    и средната стойност на ред 1
                                   ако средната стойност на ред 1 е по-голям разменяте стойностите на елементите от колоните на ред 0 и ред 1
