### ISSUE TITLE
Как да премахна имот след като е закупен

### ISSUE THREAD

**Issue by vladko194** [theVelislavKolesnichenko/CPlusPlusBasic#6]

**Comment by theVelislavKolesnichenko** [comment]
Презаписвате записа с този имот със следващия и т.н. след което намаляте броя на имотите.

Пример с масив от числа:

```c++
void deleteByIndex(int a[], int count, int delete)
{
    for(int i = delete; i < count - 1; i++)
    {
        a[i]=a[i-1];
    }
}
```

**Comment by vladko194** [comment]
Пробвах нещо подобно но след като се извърши това като отида да се изведат имотите или копира друг имот или излизат някакви странни числа

**Comment by vladko194** [comment]
и това int delete на каква стойност трябва да е равна 0?

**Comment by vladko194** [comment]
Също така за сортирането след като се сортират до главното меню ли трябва да се върнем за да го изведем с главния масив или трябва копие на главния масив с него да се изведат а главния да си седи както е

**Comment by theVelislavKolesnichenko** [comment]
връща се към главното меню за извеждане

**Comment by vladko194** [comment]
![save2](https://user-images.githubusercontent.com/10382064/71493752-e6e96300-2849-11ea-9642-b40b4bd6d57c.png)
![save1](https://user-images.githubusercontent.com/10382064/71493753-e6e96300-2849-11ea-827f-cc5df3d92dd6.png)
имам проблем със запазването на данните във файл записва ги точно както е в display функцията но при извеждането размества всичко появяват се и огромни числа все едно нищо не е въведено в тях

**Comment by vladko194** [comment]
![save3](https://user-images.githubusercontent.com/10382064/71493835-e30a1080-284a-11ea-98cc-aaabbdb186ae.png)
![save4](https://user-images.githubusercontent.com/10382064/71493836-e30a1080-284a-11ea-9f76-d38571bbd0fc.png)

**Comment by theVelislavKolesnichenko** [comment]
Данните във файла са записани на един ред

**Comment by vladko194** [comment]
Документацията само с блок схеми ли може или също и с думи можем да опишем функциите

**Comment by theVelislavKolesnichenko** [comment]
С думи от какъв тип са входните данни на функциите и какъв е изхода на функцията дали е извеждане в конзолата или връщане на резултат или записване във файл или четене от файл

другото с блок схема
