### ISSUE TITLE
Как се прави групиране по държава в курсовата работа?

### ISSUE THREAD

**Issue by vazasrozi** [theVelislavKolesnichenko/CPlusPlusBasic#7]
В курсовата работа за световното първенство по лека атлетика, подточка E е следната: Участниците от всяко състезание се групират по държави в нов масив. Как става групирането по държави?

**Comment by theVelislavKolesnichenko** [comment]
В нов масив за всяка държава се отделят само участниците от тази държава. Когато се въвеждат спортистите се въвежда по един спортист за всеки вид спорт от една държава.

**Comment by joingithubforfree** [comment]
Ако за всяка една държава добавим един спортист от всеки вид спорт, тогава какво ще напишем за "Извеждане на държавата в най много атлети".

**Comment by theVelislavKolesnichenko** [comment]
След като прочетох условието там пише как да се групират състезателите от една държава. Трябва да се направи нов масив с имената на държавите, точките които са събрани от нейните състезатели по време на състезанието и масив с атлетите, които се състезават за тази държава.

Как може информацията за Името на държавата, събраните точки и масив с атлети да се събере в една променлива ?

"Извеждане на държавата в най-много атлети" - трябва да се изведе държавата с най-много атлети. Какво ще стане ако има повече от една държава със равен най-голям брой атлети?

**Comment by vazasrozi** [comment]
Как може информацията за Името на държавата, събраните точки и масив с атлети да се събере в една променлива ? - Структура?

А как става определянето на точките? След като имаме генериран резултат в определено състезание, трябва да класираме всеки участник и така да определим точкуването?

**Comment by theVelislavKolesnichenko** [comment]
Да структора е.

Състезателите трябва да се класират. 

Според мен най-лесно ще ви е ако състезателите от един спорт са в един масив. след което този масив се подреди от най-високия към най-ниския резултат. В този случай индексите в масива определят мястото на състезателя в дисциплината.
