### ISSUE TITLE
Въпроси по създаването на документация

### ISSUE THREAD

**Issue by aetyi** [theVelislavKolesnichenko/CPlusPlusBasic#8]
Имам няколко въпроса,свързано със създаването на документацията.
В страницата за изисквания точка 2 в подточка iii не мога да разбера напълно как да ги структурирам- на всяка подточка да направя пооделно решенията на всяка част,или да направя цялото условие на част по част на функциите?
Мога ли да опиша анализа като "наръчник" или трябва само да отбележа функциите и механизмът на работене?
Документацията електронна ли трябва да бъде или листова?
На точка 4 подочка i не мога да разбера как да се  снимат "правилно" входните данни в програмата - примерно въвеждане на всяка част от функция или текстов файл със запазените данни?
На точка 3 и 4 вътре ли трябва да бъдат в документацията?
На точка 5 подточка iv предаването на определена дата по група ли трябва да се изпратят или  
тази дата е крайният срок за предаване по електронно - пощенски вид(ZIP archive)?

**Comment by theVelislavKolesnichenko** [comment]
Относно подточка iii според мен, че най-лесно ще ви бъде да направите на всяка точка по отделно решенията. 

Може да го направите като  "наръчник".

Документацията нека да е електронна.

За точка 4 , i да се направят няколко снимки на конзолата как работи програмата.

Да 3 и 4 трябва да са част от документацията.

За точка 5 iv става дума за деня в който ще защитавате проекта по този начин трябва да донесете проекта.
