### ISSUE TITLE
Как да се върна към главното меню след като се избере опция?

### ISSUE THREAD

**Issue by vazasrozi** [theVelislavKolesnichenko/CPlusPlusBasic#9]
Имам проблем с програмата - когато избера опция от менюто, вместо след края на функцията да се върне програмата към главното меню, програмата приключва. Как да го оправя? Имам break във всеки case.

**Comment by theVelislavKolesnichenko** [comment]
със цикъл чието условие е да се изпълнява докато не се избере опцията за изход от менюто
